/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tesseract.tess4j.quickstart;

import org.junit.Ignore;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test @Ignore
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
