/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.hannotify.tesseract.tess4j.quickstart;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
