/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tesseract.tess4j.quickstart;

import net.sourceforge.tess4j.ITesseract;
import net.sourceforge.tess4j.Tesseract;
import net.sourceforge.tess4j.TesseractException;

import java.io.File;

public class Library {
    public static void main(String[] args) throws TesseractException {
//        doOCR("eng", new File("src/main/resources/clean-code.png"));
//        doOCR("grc", new File("src/main/resources/new-testament.png"));
        doOCR("eng", new File("src/main/resources/joke-lowres.png"));
        doOCR("eng", new File("src/main/resources/joke-hires.png"));
    }

    private static void doOCR(String language, File image) throws TesseractException {
        ITesseract tesseract = new Tesseract();
        tesseract.setDatapath("/usr/local/Cellar/tesseract/4.0.0/share/tessdata/");
        tesseract.setLanguage(language);

        System.out.println(String.format("Processing image '%s', please wait...", image.getName()));
        String text = tesseract.doOCR(image);
        System.out.println("Done. Result:");
        System.out.println(text);
    }
}
